#Configurations
WIDTH = 1840
HEIGHT = 920
ROWS = 10
COLS = 20
MAXBLOCKS = 200
SNAKEOUTLINE = 2
BLOCKSIZE = min(WIDTH / COLS, HEIGHT / ROWS)
WIDTH = int(BLOCKSIZE*COLS)
HEIGHT = int(BLOCKSIZE*ROWS)
WINDOW = None
FRAMERATE = 30